### ISSUE TITLE
mounting throws no error, but nothing happened

### ISSUE THREAD

**Issue by manu212** [eafer/linux-apfs-oot#2]
$? returns 0
when running
mount -o vol=0 /dev/sdc2 /mnt/osx_sys_highsierra/

but "mount" shows no new mount and mountpoint is empty, tried it vor volumes 0 -3, the 4th and up throws an error, kernel 5.2.9-arch1-1-ARCH

**Comment by eafer** [comment]
Thanks for the report. I'll get back to you as soon as I can build a 5.2 kernel.

In the meantime, did you try to mount this container under an older kernel? If this is just the result of an api change it should be easy to fix. What error message did you get? Any output on dmesg?

**Comment by manu212** [comment]
I habe no oder kernel to try, I will take a look at dmesg

**Comment by eafer** [comment]
I just checked with 5.2 and the module seems to be working. Maybe encryption is enabled in your container? That's not supported yet.

If that's not the case, I will need more information, such as the parameters used to create the filesystem.

**Comment by manu212** [comment]
no encryption used. i converted hfplus under MacOS to Apfs volume

**Comment by eafer** [comment]
I have written an fsck tool, which is also packaged for AUR under the name apfsprogs-git. If you run it on your container with the -uw flags, it should report any unsupported features.

**Comment by eafer** [comment]
Any news? If you did find any unsupported features in your container, please let me know. It might be useful.

**Comment by manu212** [comment]
I have to check it today, but fdisk shows just one big unknown partition where actually exist 3 container, its a converted partition from hfplus

**Comment by eafer** [comment]
On Tue, Sep 03, 2019 at 09:45:56PM -0700, manu212 wrote:
> I have to check it today, but fdisk shows just one big unknown partition

That's normal, I wouldn't expect fdisk to be aware of APFS.  My partition is
also listed as 'unknown', but still mounts.

> where actually exist 3 container, its a converted partition from hfplus

Are you sure these are 3 separate containers, and not 3 volumes in the same
container?

**Comment by manu212** [comment]
I mean 3 volumes

**Comment by eafer** [comment]
> I mean 3 volumes

In that case it's only one partition.  The fdisk output is fine.

**Comment by eafer** [comment]
fdisk has just been patched to recognize APFS.

**Comment by eafer** [comment]
There's nothing I can do without more information, so I'm closing this now.
