### ISSUE TITLE
How does this compare with ...

### ISSUE THREAD

**Issue by Andrew-J-Larson** [eafer/linux-apfs-oot#7]
... https://github.com/sgan81/apfs-fuse ?

Is everything in sgan81's repo being used in this? Or otherway around? Or what?

And which is better to use just for accessing data (read-only) from either encrypted or unencrypted APFS volumes?

**Comment by Andrew-J-Larson** [comment]
Never mind, did some more research on my own. It appears that the repo that I mentioned has more supported features than this repo.

**Comment by eafer** [comment]
> Is everything in sgan81's repo being used in this? Or otherway around?
> Or what?

They are independent projects.

> And which is better to use just for accessing data (read-only) from either
> encrypted or unencrypted APFS volumes?

This is a kernel module, so the main advantage is (or should be) better
performance. The development tree also has some basic write support. But
the fuse version has far more read-only features, such as encryption, so
it's more useful in general.
